const controlTypes = {
  CONTROL_POWER: "CONTROL_POWER",
  CONTROL_BANK: "CONTROL_BANK",
  SET_BANK_ITEMS: "SET_BANK_ITEMS",
  SET_DISPLAY: "SET_DISPLAY",
  SET_KEYCODE: "SET_KEYCODE",
};

export default controlTypes;
